fix: update opencv-python

diff --git a/.github/workflows/opencv-python.yaml b/.github/workflows/opencv-python.yaml
--- a/.github/workflows/opencv-python.yaml
+++ b/.github/workflows/opencv-python.yaml
@@ -11,14 +11,33 @@ on:
 
 jobs:
   build:
-    name: Build opencv-python ${{ matrix.python }} ${{ matrix.platform }} wheel on ${{ matrix.os }}
+    name: Build opencv-python ${{ matrix.platform }} wheel on ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
         os: [loongarch64-abi2.0]
-        platform: ["manylinux"]
-        python: ["cp39", "cp310", "cp311", "cp312", "cp313"]
+        python-version: ['3.9']
+        platform: [loongarch64]
+        with_contrib: [0]
+        without_gui: [0]
+        build_sdist: [0]
+    env:
+      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
+      REPO_DIR: .
+      PROJECT_SPEC: opencv-python
+      MB_PYTHON_VERSION: ${{ matrix.python-version }}
+      TRAVIS_PYTHON_VERSION: ${{ matrix.python-version }}
+      MB_ML_VER: 2_38
+      TRAVIS_BUILD_DIR: ${{ github.workspace }}
+      CONFIG_PATH: travis_config.sh
+      DOCKER_IMAGE: ghcr.io/loongson-cloud-community/opencv-python-manylinux_2_38-loongarch64:20250829_abi2.0
+      USE_CCACHE: 0
+      UNICODE_WIDTH: 32
+      PLAT: loongarch64
+      SDIST: ${{ matrix.build_sdist || 0 }}
+      ENABLE_HEADLESS: ${{ matrix.without_gui }}
+      ENABLE_CONTRIB: ${{ matrix.with_contrib }}
     steps:
       - name: Check if exists
         run: |
@@ -30,8 +49,6 @@ jobs:
             version="${{ github.event.inputs.version }}"
           fi
 
-          platform="${{ matrix.platform }}"
-          python_tag="${{ matrix.python }}"
           url="https://lpypi.loongnix.cn/loongson/pypi/+simple/${pkg}/"
           upstream_url="https://pypi.org/pypi/${pkg}/json"
 
@@ -39,15 +56,15 @@ jobs:
             version="$(curl -s ${upstream_url} | jq -r '.info.version')"
           fi
 
-          if curl -s ${url} | grep ${version} | grep -q ${python_tag}-${platform}.*loongarch64; then
+          if curl -s ${url} | grep ${version} | grep -q opencv_python.*loongarch64; then
             echo "SKIP=true" >> $GITHUB_ENV
-            echo "${pkg}-${version}-${python_tag}-${platform} wheel already exists."
+            echo "${pkg}-${version}-${platform} wheel already exists."
           else
             echo "SKIP=false" >> $GITHUB_ENV
-            echo "${pkg}-${version}-${python_tag}-${platform} wheel not found, continue building."
+            echo "${pkg}-${version}-${platform} wheel not found, continue building."
           fi
 
-          echo "VERSION=${version}" >> $GITHUB_ENV
+          echo "VERSION=${version##*.}" >> $GITHUB_ENV
 
       - name: Clean workspace
         if: ${{ env.SKIP != 'true' }}
@@ -56,33 +73,31 @@ jobs:
 
       - name: Download source
         if: ${{ env.SKIP != 'true' }}
-        uses: Loongson-Cloud-Community/pypi@main
+        uses: actions/checkout@v3
         with:
-          name: opencv-python
-          version: ${{ env.VERSION }}
+          repository: opencv/opencv-python
+          ref: ${{ env.VERSION }}
+          submodules: false
 
-      - name: Build wheel
+      - name: Patch source
         if: ${{ env.SKIP != 'true' }}
         run: |
-          pip3 install -i https://lpypi.loongnix.cn/loongson/pypi/+simple cibuildwheel==2.22.0
-          cibuildwheel
+          sed -i '/^git submodule update --init multibuild[[:space:]]*$/d' scripts/build.sh
+          git submodule update --init multibuild
+          sed -i '/-e MB_ML_LIBC="\$libc" \\/a\        -e HTTPS_PROXY="$HTTPS_PROXY" \\' multibuild/travis_linux_steps.sh
+
+      - name: Build a package
+        if: ${{ env.SKIP != 'true' }}
+        run: source scripts/build.sh
         env:
-          PIP_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
-          PIP_EXTRA_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"
-          USE_CCACHE: "1"
-          CIBW_ARCHS: "loongarch64"
-          CIBW_BUILD: "${{ matrix.python }}-${{ matrix.platform }}_loongarch64"
-          CIBW_TEST_SKIP: "*"
-          CIBW_ENVIRONMENT_PASS_LINUX: |
-            PIP_INDEX_URL
-            PIP_EXTRA_INDEX_URL
-            USE_CCACHE
+          HTTPS_PROXY: ${{ secrets.PROXY_URL }}
+          HOME: /root
 
       - name: Upload wheels
         if: ${{ env.SKIP != 'true' }}
         run: |
-          ls wheelhouse/*-${{ matrix.platform }}_*.whl || exit 1
-          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/*-${{ matrix.platform }}_*.whl
+          ls wheelhouse/*.whl || exit 1
+          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/*${{ matrix.platform }}.whl
         env:
           TWINE_USERNAME: ${{ secrets.INDEX_NAME  }}
           TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}
