feat: update uv.yaml to 0.9.26

diff --git a/.github/workflows/uv.yaml b/.github/workflows/uv.yaml
--- a/.github/workflows/uv.yaml
+++ b/.github/workflows/uv.yaml
@@ -3,6 +3,14 @@ name: build uv wheel
 on:
   schedule:
     - cron: '0 17 * * *'
+  pull_request:
+    branches: ["main"]
+    paths:
+      - ".github/workflows/uv.yaml"
+  push:
+    branches: ["main"]
+    paths:
+      - ".github/workflows/uv.yaml"
   workflow_dispatch:
     inputs:
       version:
@@ -12,19 +20,19 @@ on:
 env:
   PACKAGE_NAME: uv
   MODULE_NAME: uv
+  PYTHON_VERSION: "3.11"
   CARGO_INCREMENTAL: 0
   CARGO_NET_RETRY: 10
   CARGO_TERM_COLOR: always
   RUSTUP_MAX_RETRIES: 10
 
 jobs:
-  check-wheel-exists:
+  check:
     name: Check if exists
-    runs-on: loongarch64-abi2.0
+    runs-on: ubuntu-latest
     outputs:
       version: ${{ steps.check.outputs.version }}
-      build_manylinux: ${{ steps.check.outputs.build_manylinux }}
-      build_musllinux: ${{ steps.check.outputs.build_musllinux }}
+      build: ${{ steps.check.outputs.build }}
     steps:
       - name: Check if wheels exist
         id: check
@@ -32,14 +40,14 @@ jobs:
           pkg=${{ env.PACKAGE_NAME }}
 
           check_wheel() {
-            local tag=$1
+            curl -Ls "${url}" | grep "${pkg}-${version}.*loongarch64"
 
-            if curl -Ls "${url}" | grep -q "${pkg}-${version}.*${tag}.*loongarch64"; then
-              echo "build_${tag}=false" >> $GITHUB_OUTPUT
-              echo "${tag} wheel already exists."
+            if curl -Ls "${url}" | grep -q "${pkg}-${version}.*loongarch64"; then
+              echo "build=false" >> $GITHUB_OUTPUT
+              echo "wheel already exists."
             else
-              echo "build_${tag}=true" >> $GITHUB_OUTPUT
-              echo "${tag} wheel not found, continue building."
+              echo "build=true" >> $GITHUB_OUTPUT
+              echo "wheel not found, continue building."
             fi
 
           }
@@ -59,118 +67,80 @@ jobs:
 
           echo "version=${version}" >> $GITHUB_OUTPUT
 
-          for tag in manylinux musllinux; do
-            check_wheel "$tag"
-          done
+          check_wheel
 
-  debug:
-    name: Debug outputs
-    needs: check-wheel-exists
-    runs-on: loongarch64-abi2.0
-    steps:
-      - run: |
-          echo "build_manylinux=${{ needs.check-wheel-exists.outputs.build_manylinux }}"
-          echo "build_musllinux=${{ needs.check-wheel-exists.outputs.build_musllinux }}"
-
-  download:
-    name: Download source
-    needs: check-wheel-exists
-    env:
-      version: ${{ needs.check-wheel-exists.outputs.version }}
-    runs-on: ${{ matrix.os }}
+  linux-loongarch64:
+    name: Build ${{ matrix.platform.target }} wheel
+    needs: [check]
+    runs-on: ubuntu-latest
+    if: needs.check.outputs.build == 'true'
     strategy:
-      fail-fast: false
       matrix:
-        os: [loongarch64-abi2.0]
-    if: ${{ needs.check-wheel-exists.outputs.build_manylinux == 'true' || needs.check-wheel-exists.outputs.build_musllinux == 'true' }}
+        platform:
+          - target: loongarch64-unknown-linux-gnu
+            arch: loongarch64
+            manylinux: "manylinux_2_36"
+          - target: loongarch64-unknown-linux-musl
+            arch: loongarch64
+            manylinux: "musllinux_1_2"
+
+    steps:
+      - uses: actions/checkout@v6.0.1
+        with:
+          repository: astral-sh/uv
+          ref: ${{ needs.check.outputs.version }}
+
+      - uses: actions/setup-python@v6.1.0
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+
+      - uses: astral-sh/setup-uv@v6
+        with:
+          version: "latest"
+          enable-cache: true
+      - name: "Prep README.md"
+        run: |
+          curl -sL https://github.com/loong64/uv/raw/refs/heads/main/patch_loong64.patch | git apply
+          python scripts/transform_readme.py --target pypi
+      - name: Sync Python Releases
+        run: |
+          uv run -- fetch-download-metadata.py
+        working-directory: ./crates/uv-python
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: "Build wheels"
+        uses: loong64/maturin-action@main
+        with:
+          target: ${{ matrix.platform.target }}
+          manylinux: ${{ matrix.platform.manylinux }}
+          args: --release --locked --out dist --features self-update
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.PACKAGE_NAME }}_${{ matrix.platform.manylinux }}_${{ github.sha }}
+          path: ./dist/*.whl
+
+  upload:
+    needs: [check, linux-loongarch64]
+    runs-on: loongarch64-abi2.0
+    if: needs.check.outupts.build == 'true' && github.event_name != 'pull_request'
+
     steps:
       - name: Clean workspace
         run: safe-rm -rf * .*
 
-      - name: Download source
-        uses: Loongson-Cloud-Community/pypi@main
+      - uses: actions/download-artifact@v4
         with:
-          name: ${{ env.PACKAGE_NAME }}
-          version: ${{ env.version }}
-        
-  build:
-    name: Build uv ${{ matrix.platform }} wheel on ${{ matrix.os }}
-    needs: [check-wheel-exists, download]
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - os: loongarch64-abi2.0
-            image: "lcr.loongnix.cn/pypa/manylinux_2_38_loongarch64"
-            target: "loongarch64-unknown-linux-gnu"
-            platform: "manylinux_2_38"
-          - os: loongarch64-abi2.0
-            image: "lcr.loongnix.cn/pypa/musllinux_1_2_loongarch64"
-            target: "loongarch64-unknown-linux-musl"
-            platform: "musllinux_1_2"
-    container:
-      image: ${{ matrix.image }}
-      env:
-        RUSTUP_HOME: /root/.rustup
-        CARGO_HOME: /root/.cargo
-        HTTPS_PROXY: ${{ secrets.PROXY_URL }}
-        PIPX_DEFAULT_PYTHON: /usr/local/bin/python3.11
-        SKIP: true
-    steps:
-      - name: Check if wheel exists
-        if: |
-          ${{ (matrix.platform == 'manylinux_2_38' && needs.check-wheel-exists.outputs.build_manylinux == 'true') || (matrix.platform  == 'musllinux_1_2' && needs.check-wheel-exists.outputs.build_musllinux == 'true') }}
-        run:
-          echo "SKIP=false" >> $GITHUB_ENV
-
-      - name: Install dependence
-        if: ${{ env.SKIP != 'true' }}
-        run: |
-          if command -v yum &> /dev/null; then
-            yum update -y && yum install -y perl-core openssl openssl-devel pkgconfig libatomic
-          fi
-
-      - name: Setup rust-toolchain
-        if: ${{ env.SKIP != 'true' }}
-        run: |
-          curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal
-
-      - name: Patch source
-        if: ${{ env.SKIP != 'true' && matrix.platform == 'musllinux_1_2' }}
-        run: |
-          export PATH="/root/.cargo/bin:$PATH"
-          cargo vendor
-          sed -i '/^\[patch\.crates-io\]/a rustix = { package = "rustix", version = "1.0.8", path = "vendor/rustix" }' Cargo.toml
-          cd vendor/rustix && \
-          wget -qO - https://raw.githubusercontent.com/Loongson-Cloud-Community/uv/refs/heads/dev-ruff-0.4.10/fix-rustix-STATX_A_B-is-ambiguous-error.patch | patch -p1
-
-      - name: Build wheel
-        if: ${{ env.SKIP != 'true' }}
-        run: |
-          pipx install maturin
-          export PATH="/root/.cargo/bin:$PATH"
-          maturin build --release --out dist --features self-update --target ${{ matrix.target }} --compatibility ${{ matrix.platform }}
-        env:
-          PIP_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
-          RUST_LIBC_MUSL_GEQ_1_2_3: 1
-
-      - name: Test wheel
-        if: ${{ env.SKIP != 'true' }}
-        run: |
-          pipx install --force dist/${{ env.PACKAGE_NAME }}*${{ matrix.platform }}*.whl
-          ${{ env.MODULE_NAME }} --help
-          uvx --help
+          pattern: ${{ env.PACKAGE_NAME }}_*
+          path: dist
+          merge-multiple: true
 
       - name: Upload wheel
-        if: ${{ env.SKIP != 'true' }}
         run: |
-          ls dist/${{ env.PACKAGE_NAME }}*${{ matrix.platform }}*.whl || exit 1
-          export PATH="/root/.cargo/bin:$PATH"
-          pipx install twine
-          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi dist/${{ env.PACKAGE_NAME }}*${{ matrix.platform }}*.whl
+          ls dist/${{ env.PACKAGE_NAME }}-*.whl || exit 1
+          pip install twine==6.0.1
+          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi dist/${{ env.PACKAGE_NAME }}-*.whl
         env:
-          PIP_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
-          PIP_EXTRA_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"
           TWINE_USERNAME: ${{ secrets.INDEX_NAME  }}
           TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}
